### PR TITLE
MOBILE-2612: Fix incompatibilities with Material Library

### PR DESCRIPTION
**Pull request by jamesromo-wf**
Description
---
w-mobile-kit is currently hitting some collisions with the naming in Material library. This should be fixes and the library included to avoid future issues.

What Was Changed
---
- Fixed a few naming collisions with certain extensions

Testing
---
1. Verify no functionality was changed
2. Unit tests pass. 

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jamesromo-wf** [comment]
Smithy will fail until the mobile-kit component is updated. I have it referencing a local w-mobile-kit with the branch pulled down for now.

**Comment by jeffscaturro-wf** [comment]
Do these variable renames introduce breaking changes? If so we should update the version in Marv to reflect a Major version bump.

**Comment by jordanross-wf** [comment]
+10, new names are descriptive, not conflicting with Material library, and tests pass. Merging to master.

**Pull request merged**
