### PR TITLE
MOBILE-2159: iOS: Update w-mobile-kit to swift 2.3

### PR DESCRIPTION
**Pull request by jordanross-wf**
Description
---
To be able to build with xcode 8 and use the iOS 10 simulators, our code and dependencies need to be updated to swift 2.3. This ticket should include the code conversion of the framework and example app and any fixes of issues that are found because of the code conversion. This includes updating unit tests and smithy as well.

What Was Changed
---
* Updated SnapKit pod to use 0.22.0 which is updated for Swift 2.3
* Converted code of Mobile Kit source and example app to Swift 2.3
* Fixed unit test failures that were revealed as a result of switching to Swift 2.3
* Updated podfile for Swift 2.3

Testing
---
* Make sure to run ./setup.sh script
* Test example app in Xcode 8 and verify everything works as expected
* Make sure unit tests run and pass on any iOS 10 device/simulator

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jeffscaturro-wf** [comment]
This will cause a [major version bump](http://semver.org/) in w-mobile-kit as it will be a breaking change (per discussion with @jamesromo-wf and @jordanross-wf). We will want to update the next release for Rosie/Marv when this is ready to be merged.

**Comment by jeffscaturro-wf** [comment]
@rmconsole-wf

**Comment by jeffscaturro-wf** [comment]
+10

- [ ] Unit test created or updated.
- [ ] Acceptance criteria met.
- [ ] Edge cases tested.

**Pull request merged**
