### PR TITLE
MOBILE-2529 Release w-mobile-kit 2.1.7

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [MOBILE-2519: AutoViewLayoutVC](https://github.com/Workiva/w-mobile-kit/pull/132)
* [MOBILE-2525: Add Accessibility ID's for Functional Tests](https://github.com/Workiva/w-mobile-kit/pull/133)

Requested by: @jeffscaturro-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.6...version-bump-w-mobile-kit-2-1-7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.6...2.1.7

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jeffscaturro-wf** [comment]
+1 semver

**Comment by jeffscaturro-wf** [comment]
@rmconsole-wf

**Comment by colefeisthamel-wf** [comment]
RM +1 manually checked dependencies

**Pull request merged**
