### PR TITLE
MOBILE-2656: Xcode 9/Swift 3.2

### PR DESCRIPTION
**Pull request by jamesromo-wf**
Description
---
Update the app and any dependencies to work with the new xcode beta.
If the transition isn't too difficult, also update to Swift 4. If it ends up being too much work, create an additional ticket.

What Was Changed
---
- Updated dependencies
- Fixed breaking changes
- Updated app to use Swift 3.2

Testing
---
1. Validate the library builds
2. Walk through the sample app and verify everything looks alright in iOS 11
3. Also verify the iPhone X isn't broken

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by jordanross-wf** [comment]
+10, all runs well, only issue found is the AutoCompleteTextView on an iPhone X when the keyboard is hidden. Issue is edge case-y and not broken, just minor ui glitches.

**Comment by jamesromo-wf** [comment]
@Workiva/release-management-p

**Comment by bryanrezende-wf** [comment]
+1 on code changes

**Comment by jamesromo-wf** [comment]
+10 on Jordan's changes

**Comment by jamesromo-wf** [comment]
@Workiva/release-management-p

**Comment by jamesromo-wf** [comment]
Ignore the WMobileKitExample_Example buddy build failure. That is for the example app and has been renamed to WMobileKitExample for clarity

**Comment by colefeisthamel-wf** [comment]
RM +1 manually reviewed dependencies.  Smithy is no longer being used and builds are being made with BuddyBuild.

**Pull request merged**
