### PR TITLE
MOBILE-2025, 2026 - Add SDWebImage pod for caching image requests

### PR DESCRIPTION
**Pull request by toddtarbox-wf**
Description
---
To better support showing profile images, we need a good caching library.

What Was Changed
---
Added SDWebImage pod

Testing
---
Ensure the example app works correctly

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@toddtarbox-wf, @jamesromo-wf
* A security review has not been completed, but one is required on this pull or one of its dependencies. Please request a security review from one of the approved security reviewers listed [here](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines).

**Comment by jordanross-wf** [comment]
+10, image loads properly utilizing new 3rd party lib in the example app

- [ ] Appropriate reviews.
- [ ] Unit test created or updated.
- [ ] Acceptance criteria met.
- [ ] Edge cases tested.
- [ ] Rosie has run.

Merging into `master` pending Smithy pass

**Comment by bryanhales-wf** [comment]
Security +1

**Pull request merged**
