### PR TITLE
MOBILE-2355: Increase Radiobutton performance for use in Certs

### PR DESCRIPTION
**Pull request by bryanrezende-wf**
Description
---
- Change order of actions to allow radio button to visually update faster. Needed for 2355

What Was Changed
---
- Change order of actions to allow radio button to visually update faster. Needed for 2355

Testing
---
- Regression testing around radio buttons. Ensure they still work as intended. 

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jeffscaturro-wf** [comment]
idk why smithy is failing on `ERROR:  Error installing xcov:`?

**Comment by jeffscaturro-wf** [comment]
+10 - no regressions found in radio button and it appeared to update faster.

**Comment by teresarevious-wf** [comment]
RM +1

verified dependencies manually

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
