### PR TITLE
MOBILE-2090: Update w-mobile-kit podspec to Workiva specifications

### PR DESCRIPTION
**Pull request by jamesromo-wf**
Description
---
Update the podspec in mobile kit to match the pubspec (as close as possible) specified here: https://wiki.atl.workiva.net/display/DEV/Open+Source+Software+-+OSS+-+External+Publishing+Process

What Was Changed
---
- Updated podspec to workiva specifications
    - Author name order is based on current contributions

Testing
---
1. Run ```pod lib lint --allow-warnings``` in the root and verify it passes
2. Verify everything was spelled correctly and looks professional/correct in ```WMobileKit.podspec```

---

Please Review: @Workiva/mobile

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jeffscaturro-wf** [comment]
`pod lib lint --allow-warnings` succeeds. 
Spelling looks good. 

+10 pending smithy.

**Comment by jordanross-wf** [comment]
+10 too

**Comment by jamesromo-wf** [comment]
@rmconsole-wf

**Pull request merged**
